version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000